### ISSUE TITLE
Release 27.0 broken, groups returning users

### ISSUE THREAD

**Issue by coelias** [marcospereirampj/python-keycloak#268]
Hi I've got a pipeliene that uses the latest version of python-keycloak and suddently started failing after the release v27.

I think `keycloak_admin.py(697)get_groups()` has the wrong admin url, and it is returning users.

I've sent sent PR https://github.com/marcospereirampj/python-keycloak/pull/267

**Comment by jomadu** [comment]
Having this issue too.

**Comment by einar-lanfranco** [comment]
Me too!

**Comment by JonBensi** [comment]
This appears to be the issue, line 708 of keycloak/keycloak_admin.py in the `get_groups()` function

https://github.com/marcospereirampj/python-keycloak/blob/859ea999481213cf6adf7718e56b44ee599c371a/keycloak/keycloak_admin.py#L706-L708

708 should be:
```
url = URL_ADMIN_GROUPS.format(**params_path)
```

And it looks like there's a PR out already for it #267

**Comment by waza-ari** [comment]
I'm affected by the same issue. Can confirm thought that going back to 0.26.1 works.

**Comment by jkreileder** [comment]
The same problem affects `get_group_members()`.

**Comment by ryshoooo** [comment]
This issue should be solved now with the latest release https://github.com/marcospereirampj/python-keycloak/releases/tag/0.27.1

**Comment by althaf004** [comment]
This issue is still happening with the latest version: 

https://github.com/marcospereirampj/python-keycloak/blob/859ea999481213cf6adf7718e56b44ee599c371a/keycloak/keycloak_admin.py#L706-L708

its taking from url_admin_users instead of URL_ADMIN_GROUP. Please fix this.

**Comment by ryshoooo** [comment]
> This issue is still happening with the latest version:
> 
> https://github.com/marcospereirampj/python-keycloak/blob/859ea999481213cf6adf7718e56b44ee599c371a/keycloak/keycloak_admin.py#L706-L708
> 
> its taking from url_admin_users instead of URL_ADMIN_GROUP. Please fix this.

I disagree as proven by https://github.com/marcospereirampj/python-keycloak/blob/master/src/keycloak/keycloak_admin.py#L780. Also tested every day by https://github.com/marcospereirampj/python-keycloak/blob/master/tests/test_keycloak_admin.py#L440. Make sure you have installed the latest version of the library.
